### PR TITLE
Add contributing and style guide docs

### PR DESCRIPTION
**Pull request by multani7871**

### CODE REVIEW

**Comment by ilikeadodachacha** [comment]
@multani7871 WOW cant believe you wrote all this out just now. Very helpful!

**Comment by gbatra17** [comment]
dope! why isn't this going through

**Review by gbatra17 — COMMENTED** [review]
THIS IS AWESOME.

**Review by multani7871 — COMMENTED** [review]
Thanks!

**Review by ilikeadodachacha — APPROVED** [review]

**Pull request merged**
